// <auto-generated />
using System;
using Kurator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kurator.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116181334_FixedSchemaWithBlockCurator")]
    partial class FixedSchemaWithBlockCurator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kurator.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("blocks", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.BlockCurator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer");

                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<string>("CuratorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("BlockId", "CuratorType")
                        .IsUnique();

                    b.HasIndex("BlockId", "UserId")
                        .IsUnique();

                    b.ToTable("block_curator", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommunicationChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ContactSourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullNameEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InfluenceStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("InfluenceTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastInteractionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextTouchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotesEncrypted")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int>("ResponsibleCuratorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("UsefulnessDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("CommunicationChannelId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.HasIndex("ContactSourceId");

                    b.HasIndex("InfluenceStatusId");

                    b.HasIndex("InfluenceTypeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextTouchDate");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ResponsibleCuratorId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SortOrder");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("faqs", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.InfluenceStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ContactId");

                    b.ToTable("influence_status_history", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.Interaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("text");

                    b.Property<string>("CommentEncrypted")
                        .HasColumnType("text");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuratorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InteractionTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextTouchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResultId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusChangeJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CuratorId");

                    b.HasIndex("InteractionDate");

                    b.HasIndex("InteractionTypeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ResultId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("interactions", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.ReferenceValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.HasIndex("Category", "Code")
                        .IsUnique();

                    b.HasIndex("Category", "IsActive");

                    b.ToTable("reference_values", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConflictDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DynamicsDescription")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheckDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonitoringFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextCheckDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RiskSphereId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleStatus")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ThreatSource")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("WatchOwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextCheckDate");

                    b.HasIndex("RiskSphereId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("WatchOwnerId");

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.WatchlistHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("NewRiskLevel")
                        .HasColumnType("text");

                    b.Property<string>("OldRiskLevel")
                        .HasColumnType("text");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("WatchlistId");

                    b.ToTable("watchlist_history", (string)null);
                });

            modelBuilder.Entity("Kurator.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("Kurator.Core.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kurator.Core.Entities.BlockCurator", b =>
                {
                    b.HasOne("Kurator.Core.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kurator.Core.Entities.Block", "Block")
                        .WithMany("CuratorAssignments")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.User", "User")
                        .WithMany("BlockAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Block");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kurator.Core.Entities.Contact", b =>
                {
                    b.HasOne("Kurator.Core.Entities.Block", "Block")
                        .WithMany("Contacts")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "CommunicationChannel")
                        .WithMany()
                        .HasForeignKey("CommunicationChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "ContactSource")
                        .WithMany()
                        .HasForeignKey("ContactSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "InfluenceStatus")
                        .WithMany()
                        .HasForeignKey("InfluenceStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "InfluenceType")
                        .WithMany()
                        .HasForeignKey("InfluenceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.User", "ResponsibleCurator")
                        .WithMany("Contacts")
                        .HasForeignKey("ResponsibleCuratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("CommunicationChannel");

                    b.Navigation("ContactSource");

                    b.Navigation("InfluenceStatus");

                    b.Navigation("InfluenceType");

                    b.Navigation("Organization");

                    b.Navigation("ResponsibleCurator");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Kurator.Core.Entities.FAQ", b =>
                {
                    b.HasOne("Kurator.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Kurator.Core.Entities.InfluenceStatusHistory", b =>
                {
                    b.HasOne("Kurator.Core.Entities.User", "ChangedBy")
                        .WithMany("InfluenceStatusChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.Contact", "Contact")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Kurator.Core.Entities.Interaction", b =>
                {
                    b.HasOne("Kurator.Core.Entities.Contact", "Contact")
                        .WithMany("Interactions")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.User", "Curator")
                        .WithMany("Interactions")
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "InteractionType")
                        .WithMany()
                        .HasForeignKey("InteractionTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Curator");

                    b.Navigation("InteractionType");

                    b.Navigation("Result");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Kurator.Core.Entities.Watchlist", b =>
                {
                    b.HasOne("Kurator.Core.Entities.ReferenceValue", "RiskSphere")
                        .WithMany()
                        .HasForeignKey("RiskSphereId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kurator.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.User", "WatchOwner")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("WatchOwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RiskSphere");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("WatchOwner");
                });

            modelBuilder.Entity("Kurator.Core.Entities.WatchlistHistory", b =>
                {
                    b.HasOne("Kurator.Core.Entities.User", "ChangedByUser")
                        .WithMany("WatchlistChanges")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurator.Core.Entities.Watchlist", "Watchlist")
                        .WithMany("History")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Kurator.Core.Entities.Block", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("CuratorAssignments");
                });

            modelBuilder.Entity("Kurator.Core.Entities.Contact", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Kurator.Core.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BlockAssignments");

                    b.Navigation("Contacts");

                    b.Navigation("InfluenceStatusChanges");

                    b.Navigation("Interactions");

                    b.Navigation("WatchlistChanges");

                    b.Navigation("WatchlistItems");
                });

            modelBuilder.Entity("Kurator.Core.Entities.Watchlist", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
